version: '3.7'

services:
  studyproject-webapi:
    build:
      context: .
      dockerfile: StudyProject.Webapi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - project-db
    networks:
      - project-net

  project-db:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Report
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project-net

volumes:
  pgdata:

networks:
  project-net: